/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Oefeningen": {
    get: {
      parameters: {
        query: {
          Bewerkingen?: string | null;
          Tafels?: string | null;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetOefeningenResponse"];
            "application/json": components["schemas"]["GetOefeningenResponse"];
            "text/json": components["schemas"]["GetOefeningenResponse"];
          };
        };
      };
    };
  };
  "/Resultaten": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Response"];
            "application/json": components["schemas"]["Response"];
            "text/json": components["schemas"]["Response"];
          };
        };
      };
    };
    post: {
      responses: {
        /** Success */
        201: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SaveResultaatRequest"];
          "text/json": components["schemas"]["SaveResultaatRequest"];
          "application/*+json": components["schemas"]["SaveResultaatRequest"];
        };
      };
    };
  };
  "/Resultaten/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GetResultaatResponse"];
            "application/json": components["schemas"]["GetResultaatResponse"];
            "text/json": components["schemas"]["GetResultaatResponse"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Oefening: {
      opgave?: string | null;
      resultaat?: number;
    };
    GetOefeningenResponse: {
      oefeningen?: components["schemas"]["Oefening"][] | null;
    };
    SaveResultaatFout: {
      opgave?: string | null;
      correctAntwoord?: number;
      ingevuldAntwoord?: number;
    };
    SaveResultaatRequest: {
      tafels?: number[] | null;
      bewerkingen?: string[] | null;
      doorWie?: string | null;
      punten?: number;
      maxTeBehalen?: number;
      fouten?: components["schemas"]["SaveResultaatFout"][] | null;
    };
    Resultaat: {
      id?: string;
      doorWie?: string | null;
      wanneer?: string;
      tafels?: string | null;
      bewerkingen?: string | null;
      punten?: number;
      maxTeBehalen?: number;
    };
    Response: {
      resultaten?: components["schemas"]["Resultaat"][] | null;
    };
    GetResultaatFout: {
      opgave?: string | null;
      correctAntwoord?: number;
      ingevuldAntwoord?: number;
    };
    GetResultaatResponse: {
      id?: string;
      doorWie?: string | null;
      wanneer?: string;
      tafels?: string | null;
      bewerkingen?: string | null;
      punten?: number;
      maxTeBehalen?: number;
      fouten?: components["schemas"]["GetResultaatFout"][] | null;
    };
  };
}

export interface operations {}

export interface external {}
